os: linux
dist: bionic
language: node_js
services: docker
node_js: 16
addons:
  hosts:
    - mariadb.example.com


before_install:
  - git clone https://github.com/mariadb-corporation/connector-test-machine.git


install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install -y --force nodejs-lts
        # force refresh path
        export PATH=$(cmd.exe //c "refreshenv > nul & C:\Progra~1\Git\bin\bash -c 'echo \$PATH' ")
        connector-test-machine/launch.bat -t "$srv" -v "$v" -d testn
        ;;
      linux)
        source connector-test-machine/launch.sh -t "$srv" -v "$v" -d testn -l "$local"
        ;;
    esac

env:
  global:
    - RUN_LONG_TEST=1
jobs:
  fast_finish: true
  allow_failures:
    - env: srv=build v=10.6
  include:
    - env: srv=mariadb v=10.5
      os: windows
      language: shell
    - env: srv=mariadb v=10.2 local=1
    - env: srv=mariadb v=10.3 local=1
    - env: srv=mariadb v=10.4 local=1
    - env: srv=mariadb v=10.5 local=1
    - env: srv=mariadb v=10.5 local=1
      node_js: 14
    - env: srv=mariadb v=10.5 local=1
      node_js: 12
    - env: srv=mariadb v=10.6 BENCH=1 local=1
    - if: env(CONNECTOR_TEST_SECRET_KEY)
      env: srv=maxscale
    - if: env(CONNECTOR_TEST_SECRET_KEY)
      env: srv=mariadb-es v=10.5
    - if: env(CONNECTOR_TEST_SECRET_KEY)
      env: srv=skysql RUN_LONG_TEST=0
    - if: env(CONNECTOR_TEST_SECRET_KEY)
      env: srv=skysql-ha RUN_LONG_TEST=0
    - if: env(CONNECTOR_TEST_SECRET_KEY)
      env: srv=build v=10.6
    - if: env(CONNECTOR_TEST_SECRET_KEY)
      env: srv=mysql v=5.7
    - if: env(CONNECTOR_TEST_SECRET_KEY)
      env: srv=mysql v=8.0


script:
  - npm install
  - npm install nyc -g
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        npm run coverage:test
        ;;
      linux)
        npm run test:lint
        if [ -n "$BENCH" ] ; then
          npm install promise-mysql mysql2
          npm install microtime
          npm run benchmark
        else
          npm run coverage:test
        fi
        ;;
    esac

after_success:
  - if [ -z "$BENCH" ] ; then npm run coverage:report; fi
